import type { Category, Product, SellerProfile, User, Order, Notification } from '@/types'

export const CATEGORIES: Category[] = [
  { id: 'all',         label: 'All Items',       icon: '📦' },
  { id: 'textbooks',   label: 'Textbooks',       icon: '📚' },
  { id: 'supplies',    label: 'School Supplies',  icon: '✏️' },
  { id: 'art',         label: 'Art Materials',    icon: '🎨' },
  { id: 'lab',         label: 'Lab Equipment',    icon: '🔬' },
  { id: 'electronics', label: 'Electronics',      icon: '💻' },
  { id: 'misc',        label: 'Miscellaneous',    icon: '🗂️' },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Calculus: Early Transcendentals, 8th Edition',
    category: 'textbooks',
    price: 320,
    originalPrice: 580,
    condition: 'Good',
    stock: 1,
    rating: 4.8,
    reviewCount: 24,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Mathematics',
    edition: '8th',
    description: 'Barely used. No highlights, minimal pencil marks on first chapter only. Perfect for MATH 101/102.',
    tags: ['calculus', 'textbook', 'mathematics', 'college'],
    images: [],
    createdAt: '2024-03-01',
  },
  {
    id: '2',
    title: 'Engineering Drawing Set — Complete Kit',
    category: 'supplies',
    price: 180,
    originalPrice: 350,
    condition: 'Like New',
    stock: 3,
    rating: 4.6,
    reviewCount: 11,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Engineering',
    edition: null,
    description: 'Complete drawing set. Used only once. Includes T-square, compass, set squares, and protractor.',
    tags: ['drawing', 'engineering', 'supplies'],
    images: [],
    createdAt: '2024-03-05',
  },
  {
    id: '3',
    title: 'Organic Chemistry, 9th Edition — McMurry',
    category: 'textbooks',
    price: 450,
    originalPrice: 750,
    condition: 'Fair',
    stock: 1,
    rating: 4.3,
    reviewCount: 8,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Chemistry',
    edition: '9th',
    description: 'Some highlighting in chapters 1-5. Spine intact. Great for CHEM 201.',
    tags: ['chemistry', 'textbook', 'organic', 'mcmurry'],
    images: [],
    createdAt: '2024-03-08',
  },
  {
    id: '4',
    title: 'Staedtler Mars Professional Compass Set',
    category: 'art',
    price: 220,
    originalPrice: 420,
    condition: 'Good',
    stock: 2,
    rating: 5.0,
    reviewCount: 6,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Art / Architecture',
    edition: null,
    description: 'High precision compass set. All parts complete, stored in original case.',
    tags: ['art', 'compass', 'drawing', 'architecture'],
    images: [],
    createdAt: '2024-03-10',
  },
  {
    id: '5',
    title: 'Physics for Scientists and Engineers — Serway',
    category: 'textbooks',
    price: 380,
    originalPrice: 650,
    condition: 'Good',
    stock: 1,
    rating: 4.7,
    reviewCount: 19,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'Physics',
    edition: '10th',
    description: 'Clean copy, no markings. Chapters 1-15 covered in lectures only.',
    tags: ['physics', 'textbook', 'serway', 'science'],
    images: [],
    createdAt: '2024-03-12',
  },
  {
    id: '6',
    title: 'Casio fx-991EX Scientific Calculator',
    category: 'electronics',
    price: 650,
    originalPrice: 900,
    condition: 'Like New',
    stock: 1,
    rating: 4.9,
    reviewCount: 32,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Math / Science',
    edition: null,
    description: 'Used for 1 semester only. Fully functional, original box included.',
    tags: ['calculator', 'casio', 'electronics', 'math'],
    images: [],
    createdAt: '2024-03-14',
  },
  {
    id: '7',
    title: 'Data Structures & Algorithms — Goodrich',
    category: 'textbooks',
    price: 290,
    originalPrice: 520,
    condition: 'Good',
    stock: 2,
    rating: 4.5,
    reviewCount: 14,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Computer Science',
    edition: '6th',
    description: 'Minor pencil notes in ch. 3. All pages present. Great for CS 201/301.',
    tags: ['cs', 'algorithms', 'textbook', 'programming'],
    images: [],
    createdAt: '2024-03-15',
  },
  {
    id: '8',
    title: 'Winsor & Newton Cotman Watercolor Set 12pc',
    category: 'art',
    price: 280,
    originalPrice: 450,
    condition: 'Like New',
    stock: 1,
    rating: 4.8,
    reviewCount: 9,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Fine Arts',
    edition: null,
    description: 'Half pans barely touched. Perfect for watercolor class.',
    tags: ['art', 'watercolor', 'painting', 'fine arts'],
    images: [],
    createdAt: '2024-03-16',
  },
  {
    id: '9',
    title: 'Fundamentals of Nursing, 10th Edition',
    category: 'textbooks',
    price: 420,
    originalPrice: 750,
    condition: 'Like New',
    stock: 1,
    rating: 4.9,
    reviewCount: 35,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Nursing',
    edition: '10th',
    description: 'Clean copy. Minimal highlights. Great for nursing students.',
    tags: ['nursing', 'healthcare', 'textbook'],
    images: [],
    createdAt: '2024-01-10',
  },
  {
    id: '10',
    title: 'Engineering Mechanics: Statics',
    category: 'textbooks',
    price: 380,
    originalPrice: 680,
    condition: 'Good',
    stock: 2,
    rating: 4.7,
    reviewCount: 20,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Engineering',
    edition: '5th',
    description: 'Slight wear, no missing pages.',
    tags: ['engineering', 'statics'],
    images: [],
    createdAt: '2024-02-05',
  },
  {
    id: '11',
    title: 'Computer Networking: A Top-Down Approach',
    category: 'textbooks',
    price: 500,
    originalPrice: 900,
    condition: 'Like New',
    stock: 1,
    rating: 4.8,
    reviewCount: 28,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Computer Science',
    edition: '7th',
    description: 'No markings. Slight cover crease.',
    tags: ['networking', 'IT', 'computer'],
    images: [],
    createdAt: '2024-03-02',
  },
  {
    id: '12',
    title: 'General Knowledge Encyclopedia 2023',
    category: 'misc',
    price: 250,
    originalPrice: 500,
    condition: 'Like New',
    stock: 3,
    rating: 4.5,
    reviewCount: 15,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General Knowledge',
    edition: '2023',
    description: 'Great for quick learning and trivia.',
    tags: ['general', 'knowledge', 'reference'],
    images: [],
    createdAt: '2024-01-25',
  },
  {
    id: '13',
    title: 'White Lab Gown (Medium)',
    category: 'supplies',
    price: 200,
    originalPrice: 350,
    condition: 'Like New',
    stock: 4,
    rating: 4.6,
    reviewCount: 12,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Medical',
    edition: null,
    description: 'Used once only. Clean and no stains.',
    tags: ['lab', 'gown', 'medical'],
    images: [],
    createdAt: '2024-03-12',
  },
  {
    id: '14',
    title: 'Arduino Uno R3 Starter Kit',
    category: 'electronics',
    price: 550,
    originalPrice: 900,
    condition: 'Good',
    stock: 2,
    rating: 4.8,
    reviewCount: 40,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Electronics',
    edition: null,
    description: 'Complete kit with wires and sensors. Tested working.',
    tags: ['arduino', 'electronics', 'microcontroller'],
    images: [],
    createdAt: '2024-02-18',
  },
  {
    id: '15',
    title: 'ASUS Motherboard (LGA1200)',
    category: 'electronics',
    price: 3200,
    originalPrice: 5000,
    condition: 'Like New',
    stock: 1,
    rating: 4.7,
    reviewCount: 18,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'Computer Hardware',
    edition: null,
    description: 'Working perfectly. No issues.',
    tags: ['motherboard', 'pc', 'hardware'],
    images: [],
    createdAt: '2024-01-30',
  },
  {
    id: '16',
    title: 'Data Structures and Algorithms in Java',
    category: 'textbooks',
    price: 450,
    originalPrice: 800,
    condition: 'Good',
    stock: 2,
    rating: 4.8,
    reviewCount: 25,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Computer Science',
    edition: '2nd',
    description: 'Some highlights but still very readable.',
    tags: ['programming', 'java', 'algorithms'],
    images: [],
    createdAt: '2024-03-20',
  },
  {
    id: '17',
    title: 'Civil Engineering Board Exam Reviewer',
    category: 'misc',
    price: 300,
    originalPrice: 600,
    condition: 'Like New',
    stock: 3,
    rating: 4.6,
    reviewCount: 14,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Engineering',
    edition: '2022',
    description: 'Complete reviewer. No missing pages.',
    tags: ['engineering', 'reviewer', 'civil'],
    images: [],
    createdAt: '2024-02-10',
  },
  {
    id: '18',
    title: 'Stethoscope (Classic Black)',
    category: 'supplies',
    price: 350,
    originalPrice: 600,
    condition: 'Good',
    stock: 2,
    rating: 4.7,
    reviewCount: 19,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Medical',
    edition: null,
    description: 'Working well. Slight wear only.',
    tags: ['medical', 'nursing', 'equipment'],
    images: [],
    createdAt: '2024-03-15',
  },
  {
    id: '19',
    title: 'Probability and Statistics for Computer Science',
    category: 'textbooks',
    price: 530,
    originalPrice: 950,
    condition: 'Good',
    stock: 4,
    rating: 4.2,
    reviewCount: 14,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Computer Science',
    edition: '3rd',
    description: 'Minor creases on the first few chapters. All pages present. Great for CS students struggling in statistics.',
    tags: ['cs', 'textbook', 'statistics', 'programming'],
    images: [],
    createdAt: '2025-04-03',
  },
  {
    id: '20',
    title: 'Computer Systems: A Programmer\'s Perspective',
    category: 'textbooks',
    price: 740,
    originalPrice: 1190,
    condition: 'Good',
    stock: 3,
    rating: 4.1,
    reviewCount: 14,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Computer Science',
    edition: '3rd',
    description: 'A few doodled pages. All pages present. Recommended for upcoming programmers.',
    tags: ['cs', 'systems', 'textbook', 'programming'],
    images: [],
    createdAt: '2024-10-24',
  },
  {
    id: '21',
    title: 'Drawing Mechanical Pencil Set (HB, 2H, etc.)',
    category: 'supplies',
    price: 875,
    originalPrice: 1070,
    condition: 'Like New',
    stock: 2,
    rating: 4.8,
    reviewCount: 17,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Engineering',
    edition: null,
    description: 'Complete set. Only used a few times. Includes all types.',
    tags: ['drawing', 'engineering', 'supplies'],
    images: [],
    createdAt: '2025-11-03',
  },
  {
    id: '22',
    title: 'Binder Set (6 pcs)',
    category: 'supplies',
    price: 290,
    originalPrice: 480,
    condition: 'Like New',
    stock: 5,
    rating: 4.7,
    reviewCount: 19,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General',
    edition: null,
    description: 'Not used. Assorted colors. Includes all sizes B5/A5/A4.',
    tags: ['supplies', 'binder'],
    images: [],
    createdAt: '2026-01-21',
  },
  {
    id: '23',
    title: 'Highlighter Marker Set (12 pcs)',
    category: 'supplies',
    price: 250,
    originalPrice: 400,
    condition: 'Good',
    stock: 5,
    rating: 4.4,
    reviewCount: 12,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General',
    edition: null,
    description: 'High-quality highlighters. Used a few times. Smooth ink flow and vibrant colors.',
    tags: ['supplies', 'markers'],
    images: [],
    createdAt: '2025-11-14',
  },
  {
    id: '24',
    title: 'Paintbrush Set (24 pcs)',
    category: 'art',
    price: 390,
    originalPrice: 650,
    condition: 'Good',
    stock: 2,
    rating: 4.7,
    reviewCount: 19,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Art Major',
    edition: null,
    description: 'Create smooth and precise artwork with this high-quality paintbrush set. Designed for durability and control.',
    tags: ['drawing', 'art', 'architecture'],
    images: [],
    createdAt: '2025-06-14',
  },
  {
    id: '25',
    title: 'Acrylic Markers Set (36 pcs)',
    category: 'art',
    price: 350,
    originalPrice: 700,
    condition: 'Good',
    stock: 7,
    rating: 4.4,
    reviewCount: 14,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Art Major',
    edition: null,
    description: 'Smooth, opaque ink that works on various surfaces. Perfect for art, crafts, and DIY projects.',
    tags: ['drawing', 'art', 'markers'],
    images: [],
    createdAt: '2025-09-23',
  },
  {
    id: '26',
    title: 'Pencil Set',
    category: 'art',
    price: 320,
    originalPrice: 750,
    condition: 'Good',
    stock: 1,
    rating: 4.9,
    reviewCount: 12,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Art Major',
    edition: null,
    description: 'Used a few times. Still good as new.',
    tags: ['drawing', 'art', 'pencil'],
    images: [],
    createdAt: '2024-03-23',
  },
  {
    id: '27',
    title: 'Finenolo by Deli A4 Sketchbook 120 Pages',
    category: 'art',
    price: 380,
    originalPrice: 700,
    condition: 'Fair',
    stock: 3,
    rating: 4.5,
    reviewCount: 18,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Art Major',
    edition: null,
    description: 'Still looks good as new. Only a few pages were used. Slight creases on the front pages.',
    tags: ['drawing', 'art', 'sketchbook'],
    images: [],
    createdAt: '2023-12-07',
  },
  {
    id: '28',
    title: 'Glassware Set',
    category: 'lab',
    price: 600,
    originalPrice: 950,
    condition: 'Good',
    stock: 2,
    rating: 4.9,
    reviewCount: 14,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Medicine',
    edition: null,
    description: 'A few scratches on the beakers. Used a few times. Overall good quality for second-hand equipment.',
    tags: ['lab', 'medicine', 'supplies'],
    images: [],
    createdAt: '2024-02-18',
  },
  {
    id: '29',
    title: 'Safety Equipment',
    category: 'lab',
    price: 550,
    originalPrice: 900,
    condition: 'Good',
    stock: 1,
    rating: 4.3,
    reviewCount: 17,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Medicine',
    edition: null,
    description: 'No damages on the equipment. Used a few times. Good quality for second-hand equipment.',
    tags: ['lab', 'medicine', 'supplies'],
    images: [],
    createdAt: '2024-04-26',
  },
  {
    id: '30',
    title: 'Stethoscope Kit',
    category: 'lab',
    price: 850,
    originalPrice: 1400,
    condition: 'Good',
    stock: 2,
    rating: 4.6,
    reviewCount: 21,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Medicine',
    edition: null,
    description: 'No damages. Used with care. Very good quality for second-hand equipment.',
    tags: ['lab', 'medicine', 'supplies'],
    images: [],
    createdAt: '2024-09-15',
  },
  {
    id: '31',
    title: 'Sony WH-1000XM5 Noise-Cancelling Headphones',
    category: 'electronics',
    price: 250,
    originalPrice: 620,
    condition: 'Good',
    stock: 2,
    rating: 4.4,
    reviewCount: 15,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General',
    edition: null,
    description: 'No real damages. Used a good number of times. A few scratches on the headband.',
    tags: ['electronics', 'audio', 'headphones'],
    images: [],
    createdAt: '2025-05-25',
  },
  {
    id: '32',
    title: 'Anker Nano Power Bank 10000mAh',
    category: 'electronics',
    price: 500,
    originalPrice: 870,
    condition: 'Fair',
    stock: 3,
    rating: 4.7,
    reviewCount: 17,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General',
    edition: null,
    description: 'A few scratches on the casing. Still in great condition.',
    tags: ['electronics', 'accessories'],
    images: [],
    createdAt: '2025-03-15',
  },
  {
    id: '33',
    title: 'Logitech M330 Wireless Mouse',
    category: 'electronics',
    price: 200,
    originalPrice: 480,
    condition: 'Like New',
    stock: 1,
    rating: 4.9,
    reviewCount: 14,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'General',
    edition: null,
    description: 'Barely used. No damages. Still in great condition.',
    tags: ['electronics', 'peripherals'],
    images: [],
    createdAt: '2025-08-09',
  },
  {
    id: '34',
    title: 'UV Folded Sun Umbrella',
    category: 'misc',
    price: 100,
    originalPrice: 250,
    condition: 'Good',
    stock: 1,
    rating: 4.8,
    reviewCount: 9,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'General',
    edition: null,
    description: 'Barely used. Few scratches on the handle. Still in good condition.',
    tags: ['miscellaneous'],
    images: [],
    createdAt: '2024-04-02',
  },
  {
    id: '35',
    title: 'Thermoflask Water Tumbler',
    category: 'misc',
    price: 150,
    originalPrice: 320,
    condition: 'Like New',
    stock: 2,
    rating: 4.6,
    reviewCount: 15,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'General',
    edition: null,
    description: 'Few scratches on the tumbler. Still in good condition.',
    tags: ['miscellaneous'],
    images: [],
    createdAt: '2024-02-12',
  },
]

export const SELLERS: SellerProfile[] = [
  {
    id: 's1',
    name: 'Maria Santos',
    school: 'University of Santo Tomas',
    avatar: null,
    rating: 4.9,
    totalSales: 47,
    totalListings: 12,
    responseTime: 'Within 1 hour',
    responseRate: '98%',
    memberSince: '2023',
    badges: ['Top Rated', 'Fast Responder', 'Verified Student'],
    bio: 'Selling textbooks and supplies from my first 2 years. All items well-kept!',
  },
  {
    id: 's2',
    name: 'Juan Dela Cruz',
    school: 'De La Salle University',
    avatar: null,
    rating: 4.7,
    totalSales: 31,
    totalListings: 8,
    responseTime: 'Within 3 hours',
    responseRate: '94%',
    memberSince: '2023',
    badges: ['Verified Student'],
    bio: 'CS student selling old books and equipment. Prices negotiable for bundles.',
  },
]

export const MOCK_USER: User = {
  id: 'u1',
  firstName: 'Ashley',
  lastName: 'Naval',
  email: 'ashley@email.com',
  avatar: null,
  role: 'both' as const,
  rating: 4.8,
  memberSince: '2016',
  school: 'Polytechnic University of the Philippines',
}

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2024-001',
    items: [PRODUCTS[0]],
    total: 320,
    status: 'Delivered',
    date: '2024-03-10',
    shipping: { method: 'Standard Delivery', address: '123 Mabini St, Manila' },
    payment: 'GCash',
  },
  {
    id: 'ORD-2024-002',
    items: [PRODUCTS[4], PRODUCTS[5]],
    total: 1030,
    status: 'Processing',
    date: '2024-03-18',
    shipping: { method: 'Express Delivery', address: '123 Mabini St, Manila' },
    payment: 'Credit Card **** 3232',
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'Order Update', title: 'Your order has been shipped!',       body: 'ORD-2024-002 is on its way.',                       time: '2h ago',  read: false },
  { id: 'n2', type: 'Message',      title: 'New message from Maria Santos',      body: 'Hi! Is the calculus book still available?',         time: '4h ago',  read: false },
  { id: 'n3', type: 'Promotion',    title: 'Flash Sale — Up to 50% off',         body: 'Limited time only. Browse now.',                    time: '1d ago',  read: true  },
  { id: 'n4', type: 'Review',       title: 'Leave a review for your order',      body: 'How was your purchase of Calculus 8th Ed?',         time: '2d ago',  read: true  },
]