import type { Notification } from '@/types'

// ── CATEGORIES ────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'all',       label: 'All Items',      icon: '📦' },
  { id: 'textbooks', label: 'Textbooks',      icon: '📚' },
  { id: 'supplies',  label: 'School Supplies',icon: '✏️' },
  { id: 'art',       label: 'Art Materials',  icon: '🎨' },
  { id: 'lab',       label: 'Lab Equipment',  icon: '🔬' },
  { id: 'electronics',label:'Electronics',    icon: '💻' },
  { id: 'misc',      label: 'Miscellaneous',  icon: '🗂️' },
]

export const PRODUCTS = [
  {
    id: '1',
    title: 'Calculus: Early Transcendentals, 8th Edition',
    category: 'textbooks',
    price: 320,
    originalPrice: 580,
    condition: 'Good',
    stock: 1,
    rating: 4.8,
    reviewCount: 24,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Mathematics',
    edition: '8th',
    description: 'Barely used. No highlights, minimal pencil marks on first chapter only. Perfect for MATH 101/102.',
    tags: ['calculus', 'textbook', 'mathematics', 'college'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-01',
  },
  {
    id: '2',
    title: 'Engineering Drawing Set — Complete Kit',
    category: 'supplies',
    price: 180,
    originalPrice: 350,
    condition: 'Like New',
    stock: 3,
    rating: 4.6,
    reviewCount: 11,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Engineering',
    edition: null,
    description: 'Complete drawing set. Used only once. Includes T-square, compass, set squares, and protractor.',
    tags: ['drawing', 'engineering', 'supplies'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-05',
  },
  {
    id: '3',
    title: 'Organic Chemistry, 9th Edition — McMurry',
    category: 'textbooks',
    price: 450,
    originalPrice: 750,
    condition: 'Fair',
    stock: 1,
    rating: 4.3,
    reviewCount: 8,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Chemistry',
    edition: '9th',
    description: 'Some highlighting in chapters 1-5. Spine intact. Great for CHEM 201.',
    tags: ['chemistry', 'textbook', 'organic', 'mcmurry'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-08',
  },
  {
    id: '4',
    title: 'Staedtler Mars Professional Compass Set',
    category: 'art',
    price: 220,
    originalPrice: 420,
    condition: 'Good',
    stock: 2,
    rating: 5.0,
    reviewCount: 6,
    seller: { id: 's1', name: 'Maria Santos', rating: 4.9, responseTime: 'Within 1 hour' },
    subject: 'Art / Architecture',
    edition: null,
    description: 'High precision compass set. All parts complete, stored in original case.',
    tags: ['art', 'compass', 'drawing', 'architecture'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-10',
  },
  {
    id: '5',
    title: 'Physics for Scientists and Engineers — Serway',
    category: 'textbooks',
    price: 380,
    originalPrice: 650,
    condition: 'Good',
    stock: 1,
    rating: 4.7,
    reviewCount: 19,
    seller: { id: 's4', name: 'Carlo Mendoza', rating: 4.6, responseTime: 'Within 6 hours' },
    subject: 'Physics',
    edition: '10th',
    description: 'Clean copy, no markings. Chapters 1-15 covered in lectures only.',
    tags: ['physics', 'textbook', 'serway', 'science'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-12',
  },
  {
    id: '6',
    title: 'Casio fx-991EX Scientific Calculator',
    category: 'electronics',
    price: 650,
    originalPrice: 900,
    condition: 'Like New',
    stock: 1,
    rating: 4.9,
    reviewCount: 32,
    seller: { id: 's5', name: 'Lea Gomez', rating: 4.8, responseTime: 'Within 1 hour' },
    subject: 'Math / Science',
    edition: null,
    description: 'Used for 1 semester only. Fully functional, original box included.',
    tags: ['calculator', 'casio', 'electronics', 'math'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-14',
  },
  {
    id: '7',
    title: 'Data Structures & Algorithms — Goodrich',
    category: 'textbooks',
    price: 290,
    originalPrice: 520,
    condition: 'Good',
    stock: 2,
    rating: 4.5,
    reviewCount: 14,
    seller: { id: 's2', name: 'Juan Dela Cruz', rating: 4.7, responseTime: 'Within 3 hours' },
    subject: 'Computer Science',
    edition: '6th',
    description: 'Minor pencil notes in ch. 3. All pages present. Great for CS 201/301.',
    tags: ['cs', 'algorithms', 'textbook', 'programming'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-15',
  },
  {
    id: '8',
    title: 'Winsor & Newton Cotman Watercolor Set 12pc',
    category: 'art',
    price: 280,
    originalPrice: 450,
    condition: 'Like New',
    stock: 1,
    rating: 4.8,
    reviewCount: 9,
    seller: { id: 's3', name: 'Ana Reyes', rating: 4.5, responseTime: 'Within 2 hours' },
    subject: 'Fine Arts',
    edition: null,
    description: 'Half pans barely touched. Perfect for watercolor class.',
    tags: ['art', 'watercolor', 'painting', 'fine arts'],
    images: ['/images/placeholder.jpg'],
    createdAt: '2024-03-16',
  },
]

export const SELLERS = [
  {
    id: 's1',
    name: 'Maria Santos',
    school: 'University of Santo Tomas',
    avatar: null,
    rating: 4.9,
    totalSales: 47,
    totalListings: 12,
    responseTime: 'Within 1 hour',
    responseRate: '98%',
    memberSince: '2023',
    badges: ['Top Rated', 'Fast Responder', 'Verified Student'],
    bio: 'Selling textbooks and supplies from my first 2 years. All items well-kept. Fast to respond!',
  },
  {
    id: 's2',
    name: 'Juan Dela Cruz',
    school: 'De La Salle University',
    avatar: null,
    rating: 4.7,
    totalSales: 31,
    totalListings: 8,
    responseTime: 'Within 3 hours',
    responseRate: '94%',
    memberSince: '2023',
    badges: ['Verified Student'],
    bio: 'CS student selling old books and equipment. Prices negotiable for bundles.',
  },
]

export const MOCK_USER = {
  id: 'u1',
  firstName: 'Ashley',
  lastName: 'Naval',
  email: 'ashley@email.com',
  avatar: null,
  role: 'both', // 'buyer' | 'seller' | 'both'
  rating: 4.8,
  memberSince: '2024',
  school: 'Polytechnic University of the Philippines',
}

export const MOCK_ORDERS = [
  {
    id: 'ORD-2024-001',
    items: [PRODUCTS[0]],
    total: 320,
    status: 'Delivered',
    date: '2024-03-10',
    shipping: { method: 'Standard Delivery', address: '123 Mabini St, Manila' },
    payment: 'GCash',
  },
  {
    id: 'ORD-2024-002',
    items: [PRODUCTS[4], PRODUCTS[5]],
    total: 1030,
    status: 'Processing',
    date: '2024-03-18',
    shipping: { method: 'Express Delivery', address: '123 Mabini St, Manila' },
    payment: 'Credit Card **** 3232',
  },
]

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', type: 'Order Update', title: 'Your order has been shipped!', body: 'ORD-2024-002 is on its way.', time: '2h ago', read: false },
  { id: 'n2', type: 'Message',      title: 'New message from Maria Santos', body: 'Hi! Is the calculus book still available?', time: '4h ago', read: false },
  { id: 'n3', type: 'Promotion',    title: 'Flash Sale — Up to 50% off Textbooks', body: 'Limited time only. Browse now.', time: '1d ago', read: true },
  { id: 'n4', type: 'Review',       title: 'Leave a review for your order', body: 'How was your purchase of Calculus 8th Ed?', time: '2d ago', read: true },
] as Notification[]